#   A basic travis.yml boilerplate for Django projects

language: python

python:
  - 3.5

env:
  - DJANGO=1.9.6

before_install:
  - export DJANGO_SETTINGS_MODULE=roomer.settings
  - export PYTHONPATH=$HOME/builds/kuboschek/roomer
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:


script:
  - python manage.py test