# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('live_allocation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('live_allocation', models.BooleanField(default=False)),
                ('is_tall_phase', models.BooleanField(default=False)),
                ('is_single_phase', models.BooleanField(default=False)),
                ('is_triple_phase', models.BooleanField(default=False)),
                ('points_limit', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
