# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 18:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[(b'quiet', b'quiet'), (b'tall', b'tall'), (b'disabled', b'disabled'), (b'single', b'single'), (b'double', b'double'), (b'triple', b'triple')], max_length=30)),
                ('generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roomer.College'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='associated',
            field=models.ManyToManyField(blank=True, related_name='_room_associated_+', to='roomer.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message=b'Enter a valid room code.', regex=b'[A-Z]{2}-\\d{3}')]),
        ),
        migrations.AddField(
            model_name='roomtag',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='roomer.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='roomtag',
            unique_together=set([('room', 'tag')]),
        ),
    ]
