# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roomer.models


class Migration(migrations.Migration):

    dependencies = [
        ('roomer', '0002_auto_20160508_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_level', roomer.models.IntegerRangeField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allocated_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to='roomer.Room'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_tall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_whitelisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='college',
            field=roomer.models.CollegeField(choices=[(b'NM', b'Nordmetall'), (b'C3', b'C3'), (b'KR', b'Krupp'), (b'ME', b'Mercator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='roomer.Room'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allocation_preferences',
            field=models.ManyToManyField(blank=True, through='roomer.UserPreference', to='roomer.Room'),
        ),
    ]
