# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-02 05:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomer', '0003_auto_20160510_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='seniority',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='housing_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Freshie'), (2, 'Foundation Year'), (3, '1st Year (Undergrad)'), (4, '2nd Year (Undergrad)'), (5, '3rd+ Year (Undergrad)'), (6, '1st Year (Master)'), (7, '2nd+ Year (Master)')], default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid room code.', regex='[A-Z]{2}-\\d{3}')]),
        ),
        migrations.AlterField(
            model_name='roomtag',
            name='tag',
            field=models.CharField(choices=[('quiet', 'quiet'), ('tall', 'tall'), ('disabled', 'disabled'), ('single', 'single'), ('double', 'double'), ('triple', 'triple')], max_length=30),
        ),
    ]
